name: dirving_theory_test
description: App for drivers in England

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.22.0
  path_provider: ^1.6.14
  sqflite: ^1.3.1+2


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  assets:
    - assets/questions.json
    - assets/1.jpg
    - assets/3.jpg
    - assets/4.jpg
    - assets/5.jpg
    - assets/7.jpg
    - assets/9.jpg
    - assets/13.jpg
    - assets/16.jpg
    - assets/22.jpg
    - assets/26.jpg
    - assets/28.jpg
    - assets/34.jpg
    - assets/35.jpg
    - assets/36.jpg
    - assets/38.jpg
    - assets/39.jpg
    - assets/40.jpg
    - assets/41.jpg
    - assets/50.jpg
    - assets/67.jpg
    - assets/70.jpg
    - assets/76.jpg
    - assets/82.jpg
    - assets/97.jpg
    - assets/99.jpg
    - assets/100.jpg
    - assets/102.jpg
    - assets/106.jpg
    - assets/110.jpg
    - assets/111.jpg
    - assets/112.jpg
    - assets/113.jpg
    - assets/114.jpg
    - assets/115.jpg
    - assets/116.jpg
    - assets/117.jpg
    - assets/118.jpg
    - assets/119.jpg
    - assets/120.jpg
    - assets/121.jpg
    - assets/122.jpg
    - assets/123.jpg
    - assets/124.jpg
    - assets/125.jpg
    - assets/126.jpg
    - assets/127.jpg
    - assets/128.jpg
    - assets/129.jpg
    - assets/130.jpg
    - assets/131.jpg
    - assets/132.jpg
    - assets/133.jpg
    - assets/134.jpg
    - assets/163.jpg
    - assets/164.jpg
    - assets/166.jpg
    - assets/173.jpg
    - assets/182.jpg
    - assets/194.jpg
    - assets/201.jpg
    - assets/206.jpg
    - assets/214.jpg
    - assets/215.jpg
    - assets/217.jpg
    - assets/220.jpg
    - assets/226.jpg
    - assets/229.jpg
    - assets/230.jpg
    - assets/233.jpg
    - assets/236.jpg
    - assets/237.jpg
    - assets/240.jpg
    - assets/244.jpg
    - assets/246.jpg
    - assets/247.jpg
    - assets/251.jpg
    - assets/257.jpg
    - assets/264.jpg
    - assets/266.jpg
    - assets/267.jpg
    - assets/268.jpg
    - assets/269.jpg
    - assets/270.jpg
    - assets/272.jpg
    - assets/273.jpg
    - assets/275.jpg
    - assets/277.jpg
    - assets/278.jpg
    - assets/279.jpg
    - assets/280.jpg
    - assets/281.jpg
    - assets/282.jpg
    - assets/283.jpg
    - assets/284.jpg
    - assets/285.jpg
    - assets/286.jpg
    - assets/287.jpg
    - assets/288.jpg
    - assets/289.jpg
    - assets/290.jpg
    - assets/291.jpg
    - assets/292.jpg
    - assets/293.jpg
    - assets/294.jpg
    - assets/296.jpg
    - assets/297.jpg
    - assets/298.jpg
    - assets/299.jpg
    - assets/301.jpg
    - assets/302.jpg
    - assets/303.jpg
    - assets/305.jpg
    - assets/306.jpg
    - assets/307.jpg
    - assets/308.jpg
    - assets/310.jpg
    - assets/311.jpg
    - assets/312.jpg
    - assets/313.jpg
    - assets/315.jpg
    - assets/316.jpg
    - assets/317.jpg
    - assets/318.jpg
    - assets/319.jpg
    - assets/320.jpg
    - assets/321.jpg
    - assets/322.jpg
    - assets/323.jpg
    - assets/324.jpg
    - assets/325.jpg
    - assets/328.jpg
    - assets/329.jpg
    - assets/330.jpg
    - assets/331.jpg
    - assets/332.jpg
    - assets/333.jpg
    - assets/334.jpg
    - assets/335.jpg
    - assets/336.jpg
    - assets/337.jpg
    - assets/339.jpg
    - assets/340.jpg
    - assets/341.jpg
    - assets/342.jpg
    - assets/343.jpg
    - assets/346.jpg
    - assets/347.jpg
    - assets/348.jpg
    - assets/349.jpg
    - assets/350.jpg
    - assets/352.jpg
    - assets/353.jpg
    - assets/354.jpg
    - assets/355.jpg
    - assets/356.jpg
    - assets/357.jpg
    - assets/358.jpg
    - assets/359.jpg
    - assets/360.jpg
    - assets/361.jpg
    - assets/363.jpg
    - assets/364.jpg
    - assets/365.jpg
    - assets/366.jpg
    - assets/368.jpg
    - assets/369.jpg
    - assets/370.jpg
    - assets/371.jpg
    - assets/373.jpg
    - assets/374.jpg
    - assets/376.jpg
    - assets/377.jpg
    - assets/378.jpg
    - assets/379.jpg
    - assets/380.jpg
    - assets/381.jpg
    - assets/382.jpg
    - assets/383.jpg
    - assets/384.jpg
    - assets/385.jpg
    - assets/386.jpg
    - assets/387.jpg
    - assets/388.jpg
    - assets/390.jpg
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
